goal/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [

    path('', views.index, name='index'),
    path('workouts/', views.workouts, name='workouts'),
    path('Nutrition/', views.nutrition, name='nutrition'),
    path('About/', views.about, name='about'),
    path('Contact/', views.contact, name='contact'),
    path('submited', views.submitted, name='submit')
]

gym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('stranger/', admin.site.urls),
    path('', include('goal.urls')),
]

goal/models.py
from django.db import models


class Information(models.Model):
    name = models.CharField(max_length=255)
    email = models.CharField(max_length=30)
    message = models.TextField(max_length=1000)

goal/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Information


def index(request):

    return render(request, 'index.html')


def workouts(request):
    return render(request, 'workouts.html')


def nutrition(request):
    return render(request, 'nutrition.html')


def about(request):
    return render(request, 'about.html')


def contact(request):
    return render(request, 'contact.html')


def submitted(request):
    print('form submitted...')
    name = request.POST['name']
    email = request.POST['email']
    message = request.POST['project']

    i = Information(name=name, email=email, message=message)
    i.save()
    return render(request, 'index.html')

templates/about.html
{% load static %}

<html lang="en">
<head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="author" content="perk">

      <title>About..</title>

      <!-- stylesheet -->
      <link rel="stylesheet" href="{% static 'index.css' %}">

      <!-- bootstrap cdns -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <!-- google fonts -->
      <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:100,100i,300,300i,400,400i,500,500i,700,700i" rel="stylesheet">

      <!-- for on scroll animations -->
      <link rel="stylesheet" href="{% static 'animate.css' %}">
      <script src="{% static 'js/wow.min.js' %}"></script>

</head>
<body>
    <div class="wrapper">
         <!--------------- navbar starts here --------------->
            <nav>
                  <span id="brand">
                        <a href="{% url 'polls:index' %}">Perk</a>
                  </span>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>

                  <div id="toggle">
                        <div class="span">menu</div>
                  </div>

            </nav>


            <div id="resize">
                  <div class="close-btn">close</div>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>
            </div>

         <!--------------- navbar ends here --------------->
         <!--------------- hero image starts here --------------->
        <div class="container">
            <div class="row">
                <div class="col-lg-12 about image wow fadeInUp">

                </div>
            </div>
        </div>

 <!--------------- hero image ends here --------------->
        <!--------------- hero section starts here --------------->
                <div class="container">
                    <div class="hero-content">
                        <br><br>

                        <div class="row">
                            <div class="col-lg-12">
                                <h6 class="wow fadeInUp" data-wow-delay="1s">about me.</h6><br>
                                <p class="wow fadeInUp" data-wow-delay="1s"><h6>Earned.. Not Bought</h6></p>
                                <p class="wow fadeInUp" data-wow-delay="1.5s"> After Years... of Training with Discipline, Dedication,
                                    Knowledge, Hard Work got me this physique.People say's to achieve something you have to start
                                    from zero but I say you should start from minus to get that 10 on the scale of 10....
                                </p>
                                <p class="wow fadeInUp" data-wow-delay="2s">
                                    Still today path seems to be blurry but I know the goals are hard to achieve but it's not impossible.Each of us have difficulties
                                    in life make us feel that it is impossible to reach but difficulties were also faced by the person who has achieved
                                    something in life."A stone broken by the last stroke of hammer doesn't mean that the 1st stroke was useless.." to taste the success
                                    you need lot of failure in your life.Failure are the steps towards success and success doesn't mean that you should have a heavy
                                    pocket(People's mentality).I remember once a person asked me "What is working hard ?" I smiled at him and told "It's
                                    really hard to explain 😃 but when you value your time in doing something that is improving your mental/physical health
                                    then it might be the answer you searching for.."
                                </p>
                                <p class="wow fadeInUp" data-wow-delay="2s">
                                    Change is the most important thing in someone's life.Challenges are meant to Change you without challenges
                                    life is dull and void of meaning.That feeling to grow old working on your self feels proud and happier than you used to be.
                                    Still today people tell me I am wasting my time doing useless things but this useless things(By people) taught me what is life,
                                    taught me what is hard work,taught me what is caring about animals, taught me to be silent in situations than proving a point,
                                    taught me to go temples each morning and pray to one who has created us all.My goals are different than a normal person it doesn't
                                    mean I am wasting my time on useless things. Still today when I feel like quitting I remember those people who told me I would fail
                                    and worked twice harder on my goals.Each of us have a spark in ourselves just we have to find it and yes! be
                                    the person who cares about time, Work on him/herself to improve and of course care about money...
                                </p>
                                <p class="wow fadeInUp" data-wow-delay="2s">
                                    I am hear to make people healthy to spread my knowledge about Nutrition, Workouts. Worried about your physique..? I can help you... Change yourself now to get a better future and never stop believing in God.... "Om Namah Shivay" 🙏🙏
                                </p>
                                <br>
                                <br>
                                <br>

                                <p>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>

                <!--------------- hero section ends here --------------->

                    <div class="whitespace"></div>


         <!--------------- footer starts here --------------->
             <div class="footer">
                  <div class="container">
                        <br><br>

                        <div class="collab">
                              <div class="row">
                                    <div class="col-lg-12">
                                          <p class="wow fadeInUp">Personal Trainer..</p>
                                    </div>
                              </div>
                        </div>

                        <br>

                        <div class="hr">
                              <div class="row"></div>
                        </div>

                        <br><br>

                        <div class="info">
                              <div class="row">
                                    <div class="col-lg-4" id="personal">
                                          <p class="wow fadeInUp">connect with me</p>
                                          <h4 class="wow fadeInUp" data-wow-delay="0.2s">ig @Perk_5</h4>
                                          <br><br>
                                    </div>

                                    <div class="col-lg-4" id="media">
                                          <p class="wow fadeInUp" data-wow-delay="0s">follow me</p>

                                          <ul>
                                                <li id="fb" class="wow fadeInUp" data-wow-delay="0.5s">fb</li>
                                                <li id="ig" class="wow fadeInUp" data-wow-delay="0.7s">ig</li>

                                          </ul>

                                          <br><br>
                                    </div>

                                    <div class="col-lg-4" id="address">
                                          <p class="wow fadeInUp" data-wow-delay="0s">say hello</p>
                                          <h4 class="wow fadeInUp" data-wow-delay="0.2s">prerak9359@gmail.com</h4>
                                          <br><br>
                                    </div>
                              </div>
                        </div>
                  </div>
             </div>

 <!--------------- footer ends here --------------->
        <br><br><br><br>
    </div>
 <!-- greensock cdn -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript">

            $("#toggle").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $("#resize ul li a").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $(".close-btn").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            TweenMax.from("#brand", 1, {
                delay: 0.4,
                y: 10,
                opacity: 0,
                ease: Expo.easeInOut
            })
            TweenMax.staggerFrom("#menu li a", 1, {
                delay: 0.4,
                opacity: 0,
                ease: Expo.easeInOut
                }, 0.1);

             // nav animation ends

                 new WOW().init();

    </script>

</body>
</html>

templates/contact.html
{% load static %}

<html lang="en">
<head>
     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="author" content="perk">

      <title>Contact..</title>

      <!-- stylesheet -->
      <link rel="stylesheet" href="{% static 'index.css' %}">

      <!-- bootstrap cdns -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <!-- google fonts -->
      <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:100,100i,300,300i,400,400i,500,500i,700,700i" rel="stylesheet">

      <!-- for on scroll animations -->
      <link rel="stylesheet" href="{% static 'animate.css' %}">
      <script src="{% static 'js/wow.min.js' %}"></script>

</head>
<body>

<script type="text/javascript">

function getToken(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
const csrftoken = getToken('csrftoken');

</script>

<div class="wrapper">
     <!--------------- navbar starts here --------------->
         <nav>
                  <span id="brand">
                        <a href="{% url 'polls:index' %}">Perk</a>
                  </span>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>

                  <div id="toggle">
                        <div class="span">menu</div>
                  </div>

            </nav>


            <div id="resize">
                  <div class="close-btn">close</div>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>
            </div>
 <!--------------- navbar ends here --------------->
                <div class="whitespace"></div>
 <!--------------- hero section starts here --------------->
            <div class="container">
                  <div class="hero-content">
                        <br><br>

                        <div class="row">
                              <div class="col-lg-8">

                                    <h2 class="wow fadeInUp" data-wow-delay="1s">Say Hello 👋</h2>
                                    <p class="wow fadeInUp" data-wow-delay="1.1s" >
                                        Invest on things which grows your physical/mental health and be happy always...!!!
                                    </p>
                              </div>
                        </div>
                  </div>
            </div>
 <!--------------- hero section ends here --------------->
            <!---    <div class="whitespace"></div> ----->

    <!-------------------- Form section ------------------->
      <div class="container-fluid">
                  <div class="row">
                        <div class="col-lg-8">
                              <form name="contact-form" id="contact-form" method="POST" action="{% url 'polls:submit' %}">
                                {% csrf_token %}
                                    <ul>
                                      <li class="wow fadeInUp" data-wow-delay="1.4s">
                                            <label for="contact-name">Name :</label>
                                            <div class="textarea">
                                                  <input type="text" name="name" id="contact-name" value="" required>
                                            </div>
                                      </li>

                                      <li class="wow fadeInUp" data-wow-delay="1.6s">
                                            <label for="contact-email">Email :</label>
                                            <div class="textarea">
                                                  <input type="email" name="email" id="contact-email" value="" required>
                                            </div>
                                      </li>

                                      <li class="wow fadeInUp" data-wow-delay="1.6s">
                                            <label for="contact-project">Message :</label>
                                            <div class="textarea">
                                                <textarea type="text"  name="project" id="contact-project" rows="6" value="" required></textarea>
                                            </div>
                                      </li>

                                    </ul>

                              <button type="submit" name="submit" id="contact-submit" class="send wow fadeInUp">Send Message</button>

                              </form>
                        </div>
                  </div>
            </div>

                </div>
            </div>
        </div>




        <!-------------------- Form section ends hear------------------->

      <!--------------- footer starts here --------------->

            <div class="footer">
                      <div class="container">
                            <br><br>

                            <div class="collab">
                                  <div class="row">
                                        <div class="col-lg-12">
                                              <p class="wow fadeInUp">Personal Trainer..</p>
                                        </div>
                                  </div>
                            </div>

                            <br>

                            <div class="hr">
                                  <div class="row"></div>
                            </div>

                            <br><br>

                            <div class="info">
                                  <div class="row">
                                        <div class="col-lg-4" id="personal">
                                              <p class="wow fadeInUp">connect with me</p>
                                              <h4 class="wow fadeInUp" data-wow-delay="0.2s">ig @Perk_5</h4>
                                              <br><br>
                                        </div>

                                        <div class="col-lg-4" id="media">
                                              <p class="wow fadeInUp" data-wow-delay="0s">follow me</p>

                                              <ul>
                                                    <li id="fb" class="wow fadeInUp" data-wow-delay="0.5s">fb</li>
                                                    <li id="ig" class="wow fadeInUp" data-wow-delay="0.7s">ig</li>

                                              </ul>

                                              <br><br>
                                        </div>

                                        <div class="col-lg-4" id="address">
                                              <p class="wow fadeInUp" data-wow-delay="0s">say hello</p>
                                              <h4 class="wow fadeInUp" data-wow-delay="0.2s">prerak9359@gmail.com</h4>
                                              <br><br>
                                        </div>
                                  </div>
                            </div>
                      </div>
            </div>
            <!--------------- footer ends here --------------->



    <br><br><br><br>
</div>


 <!-- greensock cdn -->

<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript">

            $("#toggle").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $("#resize ul li a").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $(".close-btn").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            TweenMax.from("#brand", 1, {
                delay: 0.4,
                y: 10,
                opacity: 0,
                ease: Expo.easeInOut
            })
            TweenMax.staggerFrom("#menu li a", 1, {
                delay: 0.4,
                opacity: 0,
                ease: Expo.easeInOut
                }, 0.1);

             // nav animation ends

                 new WOW().init();

    </script>

</body>
</html>

templates/index.html
{% load static %}

<html lang="en">
<head>
     <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <meta http-equiv="X-UA-Compatible" content="ie=edge">
      <meta name="author" content="perk">

      <title>Home..</title>
      <link rel="stylesheet" href="{% static 'index.css' %}">

     <!-- bootstrap cdns -->
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

      <!-- google fonts -->
      <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:100,100i,300,300i,400,400i,500,500i,700,700i"
            rel="stylesheet">

      <!-- terminal effect -->
      <script src="{% static 'js/t.min.js' %}"></script>

      <!-- for on scroll animations -->
      <link rel="stylesheet" href="{% static 'animate.css' %}">
      <script src="{% static 'js/wow.min.js' %}"></script>

</head>
<body>
    <div class="wrapper">
        <!--------------- navbar starts here --------------->
            <nav>
                  <span id="brand">
                        <a href="{% url 'polls:index' %}">Perk</a>
                  </span>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>

                  <div id="toggle">
                        <div class="span">menu</div>
                  </div>

            </nav>

            <div id="resize">
                  <div class="close-btn">close</div>

                  <ul id="menu">
                        <li><a href="{% url 'polls:index' %}">Home<span>.</span></a></li>
                        <li><a href="{% url 'polls:workouts' %}">Workouts<span>.</span></a></li>
                        <li><a href="{% url 'polls:nutrition' %}">Nutrition<span>.</span></a></li>
                        <li><a href="{% url 'polls:about' %}">about me<span>.</span></a></li>
                        <li><a href="{% url 'polls:contact' %}">contact<span>.</span></a></li>
                  </ul>
            </div>
            <!--------------- navbar ends here --------------->


         <!--------------- hero section starts here --------------->
            <div class="hero">
                  <div class="header">
                        <h1 class="line anim-typewriter">Welcome, How Are You </h1>
                  </div>
            </div>

            <div class="scroll-down"></div>
            <!--------------- hero section ends here --------------->

<! project section ->
        <div class="container-fluid">
                  <br><br><br>

                  <h6>Way's to Success</h6>

                  <div class="vertical"></div>
                  <br>

                  <div class="whitespace"></div>
                  <div class="whitespace"></div>

                  <div class="row">
                        <div class="col-lg-8"></div>

                        <div class="col-lg-4 project project1 wow fadeInUp"></div>
                  </div>

                  <div class="whitespace"></div>

                  <div class="row">
                        <div class="col-lg-6 project project2 wow fadeInUp"></div>

                        <div class="col-lg-6"></div>
                  </div>

                  <div class="whitespace"></div>

                  <div class="row">
                        <div class="col-lg-7"></div>

                        <div class="col-lg-4 project project3 wow fadeInUp" ></div>

                        <div class="col-lg-1"></div>
                  </div>

                  <div class="whitespace"></div>

                  <div class="row">
                        <div class="col-lg-1"></div>

                        <div class="col-lg-5 project project4 wow fadeInUp"></div>

                        <div class="col-lg-6"></div>
                  </div>

                  <div class="whitespace"></div>
            </div>
            <!--------------- projects section ends here --------------->


            <!--------------- footer starts here --------------->


         <div class="footer">
                  <div class="container">
                        <br><br>

                        <div class="collab">
                              <div class="row">
                                    <div class="col-lg-12">
                                          <p class="wow fadeInUp">Personal Trainer..</p>
                                    </div>
                              </div>
                        </div>

                        <br>

                        <div class="hr">
                              <div class="row"></div>
                        </div>

                        <br><br>

                        <div class="info">
                              <div class="row">
                                    <div class="col-lg-4" id="personal">
                                          <p class="wow fadeInUp">connect with me</p>
                                          <h4 class="wow fadeInUp" data-wow-delay="0.2s">ig @Perk_5</h4>
                                          <br><br>
                                    </div>

                                    <div class="col-lg-4" id="media">
                                          <p class="wow fadeInUp" data-wow-delay="0s">follow me</p>

                                          <ul>
                                                <li id="fb" class="wow fadeInUp" data-wow-delay="0.5s">fb</li>
                                                <li id="ig" class="wow fadeInUp" data-wow-delay="0.7s">ig</li>

                                          </ul>

                                          <br><br>
                                    </div>

                                    <div class="col-lg-4" id="address">
                                          <p class="wow fadeInUp" data-wow-delay="0s">say hello</p>
                                          <h4 class="wow fadeInUp" data-wow-delay="0.2s">prerak9359@gmail.com</h4>
                                          <br><br>
                                    </div>
                              </div>
                        </div>
                  </div>
         </div>
                    <!--------------- footer ends here --------------->

        <br><br><br><br>
    </div>
 <!-- greensock cdn -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/2.1.2/TweenMax.min.js"></script>

<script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript">

            $("#toggle").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $("#resize ul li a").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            $(".close-btn").click(function() {
                $(this).toggleClass('on');
                $("#resize").toggleClass("active");
            });

            TweenMax.from("#brand", 1, {
                delay: 0.4,
                y: 10,
                opacity: 0,
                ease: Expo.easeInOut
            })
            TweenMax.staggerFrom("#menu li a", 1, {
                delay: 0.4,
                opacity: 0,
                ease: Expo.easeInOut
                }, 0.1);

             // nav animation ends

                 new WOW().init();

    </script>
</body>
</html>